name: Build Artifacts

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install NPM Packages
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
        
      - name: Install Node modules
        run: npm install


      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r artifact_${{github.run_number}}.zip .

      - name: Upload articats
        uses: actions/upload-artifact@v3
        with:
          name: artifact_${{github.run_number}}
          path: artifact_${{github.run_number}}.zip
